import { Book } from '../types';

/**
 * Pre-extracted content from "Breath: The New Science of a Lost Art" by James Nestor.
 * This serves as the built-in featured book for Chokhmah.
 */
export const BREATH_BOOK: Book = {
  id: 'breath-james-nestor',
  title: 'Breath',
  author: 'James Nestor',
  totalChapters: 11,
  isFeatured: true,
  chapters: [
    {
      id: 'ch1',
      number: 1,
      title: 'The Experiment',
      content: `James Nestor begins his exploration of breathing by participating in a Stanford University study. For ten days, he breathes only through his mouth while researchers measure the physiological effects. The results are devastating: blood pressure spikes, stress hormones surge, snoring intensifies, and cognitive performance drops. This simple experiment reveals how profoundly our breathing patterns affect every system in our body. Nestor discovers that modern humans have become the worst breathers in the animal kingdom — and the consequences are far more serious than anyone imagined.`,
      keyConcepts: ['Mouth breathing effects', 'Stanford breathing study', 'Blood pressure and breathing', 'Modern breathing dysfunction'],
      isCompleted: false,
      timeSpentMinutes: 0,
    },
    {
      id: 'ch2',
      number: 2,
      title: 'Lost Art',
      content: `Ancient civilizations across the globe — from Chinese Taoists to Hindu yogis to Greek physicians — all understood breathing as a foundational health practice. The word "spirit" in Latin (spiritus), Greek (pneuma), Hebrew (ruach), and Sanskrit (prana) all translate to "breath." Nestor traces how this knowledge was systematically lost as modern medicine focused on treating symptoms rather than addressing the fundamental act of breathing. The ancient texts contained detailed breathing instructions that modern science is only now validating.`,
      keyConcepts: ['Ancient breathing traditions', 'Etymology of breath/spirit', 'Lost knowledge', 'East-West breathing practices'],
      isCompleted: false,
      timeSpentMinutes: 0,
    },
    {
      id: 'ch3',
      number: 3,
      title: 'A Nose Job',
      content: `The nose is a sophisticated organ that has evolved over millions of years. It filters, humidifies, and warms air before it reaches the lungs. Nasal breathing produces nitric oxide — a molecule that increases oxygen absorption by 18% and kills bacteria and viruses. The nose also regulates air pressure, which helps the lungs extract more oxygen. Nestor profiles patients who've undergone nasal surgery and researchers studying the dramatic health improvements that come from simply switching to nasal breathing. The implications are staggering: many chronic conditions may be linked to our abandonment of nasal breathing.`,
      keyConcepts: ['Nitric oxide production', 'Nasal filtration system', 'Oxygen absorption increase', 'Nasal vs mouth breathing'],
      isCompleted: false,
      timeSpentMinutes: 0,
    },
    {
      id: 'ch4',
      number: 4,
      title: 'Exhale',
      content: `Most people focus on inhaling, but the exhale may be even more important. Slow, extended exhalation activates the parasympathetic nervous system — the body's rest-and-digest mode. Nestor explores the science of CO2 tolerance and how most of us over-breathe, expelling too much carbon dioxide. Counter-intuitively, higher CO2 tolerance leads to better oxygenation through the Bohr effect. Ancient breathing practices like pranayama and Tummo meditation all emphasize controlled, extended exhalation as the path to health and mental clarity.`,
      keyConcepts: ['Parasympathetic activation', 'CO2 tolerance', 'Bohr effect', 'Extended exhalation benefits'],
      isCompleted: false,
      timeSpentMinutes: 0,
    },
    {
      id: 'ch5',
      number: 5,
      title: 'Slow',
      content: `The optimum breathing rate for humans is approximately 5.5 breaths per minute — 5.5 seconds in, 5.5 seconds out. This rate maximizes heart rate variability and activates a perfect balance between sympathetic and parasympathetic nervous systems. Remarkably, this is the exact pace of prayers and chants across multiple religious traditions: Buddhist om mani padme hum, Catholic rosary Ave Maria, and Hindu sa ta na ma. These ancient practitioners accidentally discovered the body's ideal breathing rhythm through spiritual practice.`,
      keyConcepts: ['5.5 breaths per minute', 'Heart rate variability', 'Prayer breathing rhythm', 'Sympathetic/parasympathetic balance'],
      isCompleted: false,
      timeSpentMinutes: 0,
    },
    {
      id: 'ch6',
      number: 6,
      title: 'Less',
      content: `Breathing less — not more — is the key to better health. Over-breathing (chronic hyperventilation) is an epidemic, causing anxiety, asthma, and dozens of other conditions. Konstantin Buteyko, a Ukrainian doctor, developed techniques to teach patients to reduce their breathing volume. His method has shown remarkable results in treating asthma, anxiety, and sleep disorders. The concept is counterintuitive but backed by physiology: when we breathe less, our cells actually receive more oxygen due to the Bohr effect and improved CO2 balance.`,
      keyConcepts: ['Buteyko method', 'Chronic hyperventilation', 'Breathing volume reduction', 'Less breathing = more oxygen'],
      isCompleted: false,
      timeSpentMinutes: 0,
    },
    {
      id: 'ch7',
      number: 7,
      title: 'Chew',
      content: `The human face has been shrinking for thousands of years due to the shift from hard, raw foods to soft, processed diets. This evolutionary mismatch has narrowed our airways, crowded our teeth, and made breathing harder. Nestor explores how industrial food processing created a breathing crisis. He profiles researchers and dentists who are reversing airway damage through oral appliances and chewing exercises. The connection between food texture, facial development, and breathing capacity reveals a hidden epidemic affecting billions.`,
      keyConcepts: ['Facial bone shrinkage', 'Diet and airway development', 'Oral appliance therapy', 'Evolutionary mismatch'],
      isCompleted: false,
      timeSpentMinutes: 0,
    },
    {
      id: 'ch8',
      number: 8,
      title: 'More on Less',
      content: `Building on the concept of breathing less, Nestor dives deeper into advanced techniques. Athletes who train with restricted breathing develop 15% greater endurance. Freediving champions can hold their breath for 12+ minutes through training — demonstrating the remarkable plasticity of our breathing capacity. The chapter explores how controlled CO2 exposure and breath-hold training can improve athletic performance, reduce anxiety, and enhance overall health. These techniques, once considered fringe, are gaining mainstream scientific validation.`,
      keyConcepts: ['Restricted breathing training', 'Freediving science', 'CO2 training adaptations', 'Athletic performance gains'],
      isCompleted: false,
      timeSpentMinutes: 0,
    },
    {
      id: 'ch9',
      number: 9,
      title: 'Hold It',
      content: `Breath-holding triggers a cascade of beneficial physiological responses: increased red blood cell production, spleen contraction releasing stored oxygen, and dramatic improvements in CO2 tolerance. Nestor profiles Wim Hof — the "Ice Man" — who uses aggressive breathing and cold exposure to consciously control his immune system. Scientific studies confirmed Hof's claims: his method allowed subjects to suppress inflammatory responses on demand. The implications suggest that through breathing alone, we may have far more control over our autonomic nervous system than previously believed.`,
      keyConcepts: ['Wim Hof method', 'Spleen contraction response', 'Immune system control', 'Autonomic nervous system access'],
      isCompleted: false,
      timeSpentMinutes: 0,
    },
    {
      id: 'ch10',
      number: 10,
      title: 'Fast, Slow, and Not at All',
      content: `Nestor explores the extremes of breathing: Tummo meditation (inner fire breathing that raises body temperature), Sudarshan Kriya (rhythmic breathing that treats depression), and the practice of breathlessness found in advanced meditation states. These practices produce measurable changes in brain waves, body temperature, and neurochemistry. The chapter reveals that breathing is not just a metabolic function but a direct interface between consciousness and physiology. Every emotional state has a corresponding breathing pattern — and by changing the pattern, we can change the state.`,
      keyConcepts: ['Tummo meditation', 'Sudarshan Kriya', 'Breath-emotion connection', 'Consciousness interface'],
      isCompleted: false,
      timeSpentMinutes: 0,
    },
    {
      id: 'ch11',
      number: 11,
      title: 'A Last Breath',
      content: `In the final chapter, Nestor synthesizes his journey and presents a practical breathing protocol. He returns to the Stanford lab for a follow-up experiment — this time breathing only through his nose for ten days. The results are the mirror opposite of the mouth-breathing trial: blood pressure normalizes, snoring vanishes, cognitive performance improves. The message is clear: breathing correctly is the foundation of health, and the tools to do so have been available for thousands of years. We simply need to remember what ancient civilizations knew all along.`,
      keyConcepts: ['Nasal breathing recovery', 'Practical breathing protocol', 'Health normalization', 'Ancient wisdom validated'],
      isCompleted: false,
      timeSpentMinutes: 0,
    },
  ],
};

export const DAILY_WISDOM_QUOTES = [
  { text: 'The beginning of wisdom is this: Get wisdom.', source: 'Proverbs 4:7' },
  { text: 'The fear of the Lord is the beginning of knowledge.', source: 'Proverbs 1:7' },
  { text: 'Wisdom is more precious than rubies.', source: 'Proverbs 8:11' },
  { text: 'A wise person is full of strength.', source: 'Proverbs 24:5' },
  { text: 'The wise store up knowledge.', source: 'Proverbs 10:14' },
  { text: 'Plans fail for lack of counsel, but with many advisers they succeed.', source: 'Proverbs 15:22' },
  { text: 'Commit your work to the Lord, and your plans will be established.', source: 'Proverbs 16:3' },
  { text: 'Iron sharpens iron, and one person sharpens another.', source: 'Proverbs 27:17' },
  { text: 'The heart of the discerning acquires knowledge.', source: 'Proverbs 18:15' },
  { text: 'Whoever walks with the wise becomes wise.', source: 'Proverbs 13:20' },
  { text: 'Better is wisdom than jewels, and all that you may desire cannot compare.', source: 'Proverbs 8:11' },
  { text: 'A gentle answer turns away wrath, but a harsh word stirs up anger.', source: 'Proverbs 15:1' },
  { text: 'Trust in the Lord with all your heart and lean not on your own understanding.', source: 'Proverbs 3:5' },
  { text: 'The tongue of the wise commends knowledge.', source: 'Proverbs 15:2' },
];
