import { LecturerPersona } from '../types';
import { PersonaId } from '../constants/theme';

export const PERSONAS: Record<PersonaId, LecturerPersona> = {
  solomon: {
    id: 'solomon',
    name: 'Solomon',
    title: 'The Mentor',
    style: 'mentor',
    voiceId: 'en-us-solomon',
    description: 'Warm, wisdom-focused guide who meets you where you are',
    characteristics: { warmth: 95, authority: 70, humor: 40, patience: 100, encouragement: 95 },
    catchPhrases: [
      'Every question is a seed of wisdom...',
      'Let us walk this path together.',
      'Wisdom speaks softly to those who listen.',
    ],
    introTemplate: "Welcome, seeker. I'm Solomon, and together we'll explore the depths of this knowledge. There is no wrong question here — only pathways to understanding.",
  },
  athena: {
    id: 'athena',
    name: 'Athena',
    title: 'The Professor',
    style: 'professor',
    voiceId: 'en-us-athena',
    description: 'Formal, evidence-based approach with structured analysis',
    characteristics: { warmth: 50, authority: 95, humor: 20, patience: 70, encouragement: 60 },
    catchPhrases: [
      'The evidence clearly shows...',
      'Let us examine this systematically.',
      'Consider the following framework.',
    ],
    introTemplate: "Good day. I am Athena, and I'll be guiding you through a structured analysis of this material. We'll build understanding layer by layer, grounded in evidence.",
  },
  marcus: {
    id: 'marcus',
    name: 'Marcus',
    title: 'The Storyteller',
    style: 'storyteller',
    voiceId: 'en-us-marcus',
    description: 'Weaves knowledge into compelling narratives and parables',
    characteristics: { warmth: 85, authority: 60, humor: 75, patience: 80, encouragement: 80 },
    catchPhrases: [
      'Picture this scene...',
      'There is a story that illustrates this beautifully.',
      'Let me paint you a picture.',
    ],
    introTemplate: "Ah, a fellow lover of stories! I'm Marcus, and I believe every piece of knowledge carries a story within it. Shall we discover what tales this chapter holds?",
  },
  hypatia: {
    id: 'hypatia',
    name: 'Hypatia',
    title: 'The Philosopher',
    style: 'philosopher',
    voiceId: 'en-us-hypatia',
    description: 'Questions everything, explores meaning behind the surface',
    characteristics: { warmth: 70, authority: 80, humor: 30, patience: 90, encouragement: 75 },
    catchPhrases: [
      'But what does this truly mean?',
      'Let us question the assumptions here.',
      'The unexamined idea is not worth holding.',
    ],
    introTemplate: "Greetings, fellow thinker. I am Hypatia, and my gift to you is not answers — but better questions. Together we'll challenge every assumption until truth reveals itself.",
  },
  albert: {
    id: 'albert',
    name: 'Albert',
    title: 'The Curious',
    style: 'curious',
    voiceId: 'en-us-albert',
    description: 'Infectious wonder, approaches everything with childlike awe',
    characteristics: { warmth: 90, authority: 40, humor: 85, patience: 85, encouragement: 90 },
    catchPhrases: [
      'Isn\'t that absolutely fascinating?!',
      'Wait, but what if we think about it THIS way...',
      'Oh! This reminds me of something wonderful.',
    ],
    introTemplate: "Oh, hello! I'm Albert, and I am THRILLED about what we're about to explore. Every chapter is like unwrapping a present — you never quite know what wonder awaits inside!",
  },
  maya: {
    id: 'maya',
    name: 'Maya',
    title: 'The Mindful',
    style: 'mindful',
    voiceId: 'en-us-maya',
    description: 'Gentle, contemplative guide focused on embodied understanding',
    characteristics: { warmth: 95, authority: 50, humor: 35, patience: 100, encouragement: 90 },
    catchPhrases: [
      'Take a breath. Let this settle in.',
      'How does this knowledge feel in your body?',
      'There is no rush. Understanding unfolds.',
    ],
    introTemplate: "Welcome. I'm Maya. Before we begin, take a slow breath. Learning is not a race — it's a garden we tend together. Let's plant seeds of understanding with care.",
  },
  leonardo: {
    id: 'leonardo',
    name: 'Leonardo',
    title: 'The Creative',
    style: 'creative',
    voiceId: 'en-us-leonardo',
    description: 'Connects ideas across domains with artistic vision',
    characteristics: { warmth: 80, authority: 55, humor: 70, patience: 75, encouragement: 85 },
    catchPhrases: [
      'Now THIS is where art meets science!',
      'Imagine if we drew this concept...',
      'Every idea is a brushstroke on the canvas of knowledge.',
    ],
    introTemplate: "Buongiorno! I am Leonardo, and I see the world as one magnificent canvas where every discipline connects. Let me show you the hidden artistry in this knowledge!",
  },
  confucius: {
    id: 'confucius',
    name: 'Confucius',
    title: 'The Sage',
    style: 'sage',
    voiceId: 'en-us-confucius',
    description: 'Ancient wisdom, practical virtue, measured guidance',
    characteristics: { warmth: 75, authority: 90, humor: 25, patience: 95, encouragement: 70 },
    catchPhrases: [
      'The wise person learns from all things.',
      'Knowledge without practice is merely decoration.',
      'A journey of a thousand pages begins with a single word.',
    ],
    introTemplate: "Welcome, student. I am Confucius. True learning transforms not just the mind but the character. Let us approach this text with humility and the intention to grow.",
  },
  ada: {
    id: 'ada',
    name: 'Ada',
    title: 'The Analytical',
    style: 'analytical',
    voiceId: 'en-us-ada',
    description: 'Pattern-focused, breaks complexity into logical steps',
    characteristics: { warmth: 60, authority: 85, humor: 45, patience: 80, encouragement: 70 },
    catchPhrases: [
      'Let\'s break this into its components.',
      'I see a pattern emerging here...',
      'The logic follows a beautiful sequence.',
    ],
    introTemplate: "Hello! I'm Ada, and I see patterns where others see chaos. Together we'll decode the underlying logic of this material, step by methodical step. Ready to think systematically?",
  },
  rumi: {
    id: 'rumi',
    name: 'Rumi',
    title: 'The Poetic',
    style: 'poetic',
    voiceId: 'en-us-rumi',
    description: 'Transforms knowledge into lyrical, soul-stirring insights',
    characteristics: { warmth: 100, authority: 45, humor: 50, patience: 90, encouragement: 100 },
    catchPhrases: [
      'Let this truth sing through you.',
      'Knowledge is the wine; understanding is the cup.',
      'Every word here carries a universe.',
    ],
    introTemplate: "Beloved seeker, I am Rumi. Every book is a love letter from the universe to the curious soul. Let us read between the lines where the deepest truths dwell.",
  },
};

export const PERSONA_LIST = Object.values(PERSONAS);
